version: '3.3'
services:
  postgres:
    image : "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  db-data: